routes/index.py
import os
import uuid

from flask import (
    render_template,
    request,
    redirect,
    session,
    url_for,
    Blueprint,
    abort,
    send_from_directory,
    current_app)
from werkzeug.datastructures import FileStorage

from models.reply import Replys
from models.topic import Topics
from models.user import User
from routes import current_user, cache
from routes import current_user

import json

from utils import log

main = Blueprint('index', __name__)

"""
用户在这里可以
    访问首页
    注册
    登录

用户登录后, 会写入 session, 并且定向到 /profile
"""

import gevent
import time


@main.route("/")
def index():
    # t = threading.Thread()
    # t.start()
    # gevent.spawn()
    time.sleep(0.5)
    print('time type', time.sleep, gevent.sleep)
    u = current_user()
    return render_template("login.html", user=u)


@main.route("/register/view")
def register_index():

    return render_template('signup.html')


@main.route("/register/send", methods=['POST'])
def register():
    form = request.form.to_dict()
    # 用类函数来判断
    u = User.register(form)
    return redirect(url_for('.index'))


@main.route("/login", methods=['POST'])
def login():
    form = request.form
    u = User.validate_login(form)
    if u is None:
        return redirect(url_for('.index'))
    else:
        # session 中写入 user_id
        session_id = str(uuid.uuid4())
        key = 'session_id_{}'.format(session_id)
        log('index login key <{}> user_id <{}>'.format(key, u.id))
        cache.set(key, u.id)

        redirect_to_index = redirect(url_for('topic.index'))
        response = current_app.make_response(redirect_to_index)
        response.set_cookie('session_id', value=session_id)
        # 转到 topic.index 页面
        return response
        # session['user_id'] = u.id
        # return redirect(url_for('topic.index'))


def created_topic(user_id):
    # O(n)
    ts = Topics.all(user_id=user_id)
    return ts
    #
    # k = 'created_topic_{}'.format(user_id)
    # if cache.exists(k):
    #     v = cache.get(k)
    #     ts = json.loads(v)
    #     return ts
    # else:
    #     ts = Topic.all(user_id=user_id)
    #     v = json.dumps([t.json() for t in ts])
    #     cache.set(k, v)
    #     return ts


def replied_topic(user_id):
    # O(k)+O(m*n)
    rs = Replys.all(user_id=user_id)
    ts = []
    for r in rs:
        t = Topics.one(id=r.topic_id)
        ts.append(t)
    return ts
    #
    #     sql = """
    # select * from topic
    # join reply on reply.topic_id=topic.id
    # where reply.user_id=1
    # """
    # k = 'replied_topic_{}'.format(user_id)
    # if cache.exists(k):
    #     v = cache.get(k)
    #     ts = json.loads(v)
    #     return ts
    # else:
    #     # ts = Topic.select()
    #     #   .join(Reply, 'id', 'topic_id')
    #     #   .where(user_id=user_id)
    #     #   .all()
    #     rs = Reply.all(user_id=user_id)
    #     ts = []
    #     for r in rs:
    #         t = Topic.one(id=r.topic_id)
    #         ts.append(t)
    #
    #     v = json.dumps([t.json() for t in ts])
    #     cache.set(k, v)
    #
    #     return ts


@main.route('/profile')
def profile():
    print('running profile route')
    u = current_user()
    if u is None:
        return redirect(url_for('.index'))
    else:
        created = created_topic(u.id)
        replied = replied_topic(u.id)
        return render_template(
            'profile.html',
            user=u,
            created=created,
            replied=replied
        )


@main.route('/user/<int:id>')
def user_detail(id):
    u = User.one(id=id)
    if u is None:
        abort(404)
    else:
        return render_template('profile.html', user=u)


@main.route('/image/add', methods=['POST'])
def avatar_add():
    file: FileStorage = request.files['avatar']
    # file = request.files['avatar']
    # filename = file.filename
    # ../../root/.ssh/authorized_keys
    # images/../../root/.ssh/authorized_keys
    # filename = secure_filename(file.filename)
    suffix = file.filename.split('.')[-1]
    if suffix not in ['gif', 'jpg', 'jpeg']:
        abort(400)
        log('不接受的后缀, {}'.format(suffix))
    else:
        filename = '{}.{}'.format(str(uuid.uuid4()), suffix)
        path = os.path.join('images', filename)
        file.save(path)

        u = current_user()
        User.update(u.id, image='/images/{}'.format(filename))

        return redirect(url_for('.profile'))


@main.route('/images/<filename>')
def image(filename):
    # 不要直接拼接路由，不安全，比如
    # http://localhost:3000/images/..%5Capp.py
    # path = os.path.join('images', filename)
    # print('images path', path)
    # return open(path, 'rb').read()
    # if filename in os.listdir('images'):
    #     return
    return send_from_directory('images', filename)

routes/reset.py
import os
import uuid

# from celery.events import receiver
from flask import (
    render_template,
    request,
    redirect,
    session,
    url_for,
    Blueprint,
    abort,
    send_from_directory,
    current_app)
from werkzeug.datastructures import FileStorage

from config import admin_mail
from models.message import Messages, send_mail
from models.user import User
from routes import current_user, csrf_required, cache

import json

from utils import log


main = Blueprint('reset', __name__)


@csrf_required
@main.route('/view')
def index():

    return render_template('forgot-password.html')


@main.route('/send', methods=["POST"])
def send():
    # 获得用户名
    # 通过用户名获得用户id
    form = request.form.to_dict()
    name = form['username']
    # log('username', name)
    u = User.one(username=name)
    # u = current_user()
    # 生成token
    token = str(uuid.uuid4())
    # csrf_tokens[token] = u.id
    id = u.id
    cache.set(token, id)
    # 发送邮件
    # log('csrf_tokens', csrf_tokens)
    receiver: User = User.one(id=u.id)
    send_mail(
        subject='修改密码',
        author=admin_mail,
        to=receiver.email,
        content='{}\r\nhttps://www.treasutre.xyz/reset/edit?token={}'.format(u.username, token),
    )
    return render_template('login.html')


@main.route('/edit')
def update_view():
    return render_template('reset.html')


@csrf_required
@main.route('/update', methods=["POST", "GET"])
def update():
    form = request.form.to_dict()
    log('form', form)
    token = str(request.referrer).split('=')[-1]
    # log('token', token, request.referrer, csrf_tokens)
    # user_id = csrf_tokens[token]
    user_id = cache.get(token)
    u = User.one(id=user_id)
    new_password = User.salted_password(form['password'])
    User.update(u.id, password=new_password)

    return render_template('login.html')

routes/setting.py
import os
import uuid

from flask import (
    render_template,
    request,
    redirect,
    session,
    url_for,
    Blueprint,
    abort,
    send_from_directory,
    current_app)
from werkzeug.datastructures import FileStorage

from models.user import User
from routes import current_user, csrf_required

import json

from utils import log

main = Blueprint('setting', __name__)

"""
用户在这里可以
    访问首页
    注册
    登录

用户登录后, 会写入 session, 并且定向到 /profile
"""

import gevent
import time


@main.route("/")
def index():
    # t = threading.Thread()
    # t.start()
    # gevent.spawn()
    time.sleep(0.5)
    print('time type', time.sleep, gevent.sleep)
    u = current_user()
    return render_template("setting.html", user=u)


@main.route('/image/add', methods=['POST'])
def avatar_add():
    file: FileStorage = request.files['avatar']
    # file = request.files['avatar']
    # filename = file.filename
    # ../../root/.ssh/authorized_keys
    # images/../../root/.ssh/authorized_keys
    # filename = secure_filename(file.filename)
    suffix = file.filename.split('.')[-1]
    if suffix not in ['gif', 'jpg', 'jpeg']:
        abort(400)
        log('不接受的后缀, {}'.format(suffix))
    else:
        filename = '{}.{}'.format(str(uuid.uuid4()), suffix)
        path = os.path.join('images', filename)
        file.save(path)

        u = current_user()
        User.update(u.id, image='/images/{}'.format(filename))

        return redirect(url_for('index.profile'))


@main.route('/images/<filename>')
def image(filename):
    # 不要直接拼接路由，不安全，比如
    # http://localhost:3000/images/..%5Capp.py
    # path = os.path.join('images', filename)
    # print('images path', path)
    # return open(path, 'rb').read()
    # if filename in os.listdir('images'):
    #     return
    return send_from_directory('images', filename)


@main.route('/re_info', methods=['POST'])
def re_info():
    form = request.form
    u = current_user()
    if form['username'] != '':
        User.update(u.id, username=form['username'])

    if form['sign'] != '':
        User.update(u.id, sign=form['sign'])

    return render_template("setting.html", user=u)


@csrf_required
@main.route('/password', methods=["POST"])
def update():
    form = request.form
    log('form', form)
    u = current_user()
    new_password = User.salted_password(form['password'])
    User.update(u.id, password=new_password)

    return render_template("login.html")

routes/topic.py
from flask import (
    render_template,
    request,
    redirect,
    url_for,
    Blueprint,
)

from routes import *

from models.topic import Topics
from models.board import Board

main = Blueprint('topic', __name__)


@main.route("/")
def index():
    u = current_user()
    if u is not None:
        board_id = int(request.args.get('board_id', -1))
        if board_id == -1:
            ms = Topics.all()
        else:
            ms = Topics.all(board_id=board_id)
        token = new_csrf_token()
        bs = Board.all()
        u = current_user()
        return render_template('topic/index.html', ms=ms, token=token, bs=bs, bid=board_id, user=u)
    else:
        return render_template('login.html')


@main.route('/<int:id>')
def detail(id):
    m = Topics.get(id)
    b = Board.one(id=m.board_id)
    # 传递 topic 的所有 reply 到 页面中
    return render_template("topic/detail.html", topic=m, b=b)


@main.route("/delete")
@csrf_required
# @author_required
def delete():
    id = int(request.args.get('id'))
    u = current_user()
    print('删除 topic 用户是', u, id)
    Topics.delete(id)
    return redirect(url_for('.index'))


@main.route("/new")
def new():
    # print('board id', request.args.get('board_id'))
    board_id = int(request.args.get('board_id'))
    bs = Board.all()
    # return render_template("topic/new.html", bs=bs, bid=board_id)
    token = new_csrf_token()
    # token =
    return render_template("topic/new.html", bs=bs, token=token, bid=board_id)


@main.route("/add", methods=["POST"])
@csrf_required
def add():
    form = request.form.to_dict()
    u = current_user()
    Topics.new(form, user_id=u.id)
    return redirect(url_for('.index'))

templates/forgot-password.html
<!DOCTYPE html>
<head>
	<title>Forgot Password</title>
	<meta name="keywords" content="" />
	<meta name="description" content="" />
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	
	<link href="/static/css-1/font-awesome.min.css" rel="stylesheet" type="text/css">
	<link href="/static/css-1/bootstrap.min.css" rel="stylesheet" type="text/css">
	<link href="/static/css-1/bootstrap-theme.min.css" rel="stylesheet" type="text/css">
	<link href="/static/css-1/templatemo_style.css" rel="stylesheet" type="text/css">
    <link href="/static/css/style.css" rel="stylesheet" type="text/css">
</head>
<body class="templatemo-bg-gray">
	<div class="container">
		<div class="col-md-12">
			<h1 class="margin-bottom-15">Forgot password?</h1>
			<form class="form-horizontal templatemo-forgot-password-form templatemo-container" role="form" action="/reset/send" method="post">
				<div class="form-group">
		          <div class="col-md-12">
		          	Please enter your username that you registered in our website.
		          </div>
		        </div>		
		        <div class="form-group">
		          <div class="col-md-12">
		            <input type="text" class="form-control" id="username" placeholder="Your username" name="username">
		          </div>              
		        </div>
		        <div class="form-group">
		          <div class="col-md-12">
		            <input type="submit" value="Submit" class="btn btn-danger">
                    <br><br>
                    <a href="/">or Login</a>
{#                    <a href="login-2.html">Login Two</a>#}
		          </div>
		        </div>
		      </form>
		</div>
	</div>
<div class="bottom">
    <a href="http://beian.miit.gov.cn" target="_blank">沪ICP备19029249号-1</a>
</div>
</body>
</html>

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>bbs club</title>
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
</head>
<body>
    <form class="form-horizontal" method="post" action="{{ url_for('index.register') }}">
        <div class="control-group">
            <label class="control-label">用户名</label>
            <div class="controls">
                <input type="text" class="input-xlarge" name="username">
            </div>
        </div>
        <div class="control-group">
            <label class="control-label">密码</label>
            <div class="controls">
                <input type="text" class="input-xlarge" name="password">
            </div>
        </div>
        <div class="form-actions">
            <input type="submit" class="span-primary" value="注册">
        </div>
    </form>
    <form class="form-horizontal" method="post" action="{{ url_for('index.login') }}">
        <div class="control-group">
            <label class="control-label">用户名</label>
            <div class="controls">
                <input type="text" class="input-xlarge" name="username">
            </div>
        </div>
        <div class="control-group">
            <label class="control-label">密码</label>
            <div class="controls">
                <input type="text" class="input-xlarge" name="password">
                <span>
                    <a href="/reset/send">忘记密码？</a>
                </span>
            </div>
        </div>
        <div class="form-actions">
            <input type="submit" class="span-primary" value="登录">
        </div>

    </form>
    <form class="form-horizontal" method="post" action="/reset/send">
        <div class="control-group">
            <label class="control-label">用户名</label>
            <div class="controls">
                <input type="text" class="input-xlarge" name="username">
            </div>
        </div>
        <div class="form-actions">
            <input type="submit" class="span-primary" value="修改密码">
        </div>
    </form>
</body>
</html>

templates/login.html
<!DOCTYPE html>
<head>
	<title>Login One</title>
	<meta name="keywords" content="" />
	<meta name="description" content="" />
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	
	<link href="/static/css-1/font-awesome.min.css" rel="stylesheet" type="text/css">
	<link href="/static/css-1/bootstrap.min.css" rel="stylesheet" type="text/css">
	<link href="/static/css-1/bootstrap-theme.min.css" rel="stylesheet" type="text/css">
	<link href="/static/css-1/templatemo_style.css" rel="stylesheet" type="text/css">
    <link href="/static/css/style.css" rel="stylesheet" type="text/css">
</head>
<body class="templatemo-bg-gray">
	<div class="container">
		<div class="col-md-12">
			<h1 class="margin-bottom-15">Welcome</h1>
			<form class="form-horizontal templatemo-container templatemo-login-form-1 margin-bottom-30" role="form" action="{{ url_for('index.login') }}" method="post">
		        <div class="form-group">
		          <div class="col-xs-12">		            
		            <div class="control-wrapper">
{#		            	<label for="username" class="control-label fa-label"><i class="fa fa-user fa-medium"></i></label>#}
		            	<input type="text" class="form-control" id="username"
                               placeholder="username" name="username" value="popop">
		            </div>		            	            
		          </div>              
		        </div>
		        <div class="form-group">
		          <div class="col-md-12">
		          	<div class="control-wrapper">
{#		            	<label for="password" class="control-label fa-label"><i class="fa fa-lock fa-medium"></i></label>#}
		            	<input type="password" class="form-control" id="password"
                               placeholder="password" name="password" value="123">
		            </div>
		          </div>
		        </div>
		        <div class="form-group">
		          <div class="col-md-12">
	             	<div class="checkbox control-wrapper">
	                	<label>
	                  		<input type="checkbox"> Remember me
                		</label>
	              	</div>
		          </div>
		        </div>
		        <div class="form-group">
		          <div class="col-md-12">
		          	<div class="control-wrapper">
		          		<input type="submit" value="Log in" class="btn btn-info">
		          		<a href="/reset/view" class="text-right pull-right">Forgot password?</a>
		          	</div>
		          </div>
		        </div>
{#		        <hr>#}
{#		        <div class="form-group">#}
{#		        	<div class="col-md-12">#}
{#		        		<label>Login with: </label>#}
{#		        		<div class="inline-block">#}
{#		        			<a href="#"><i class="fa fa-facebook-square login-with"></i></a>#}
{#			        		<a href="#"><i class="fa fa-twitter-square login-with"></i></a>#}
{#			        		<a href="#"><i class="fa fa-google-plus-square login-with"></i></a>#}
{#			        		<a href="#"><i class="fa fa-tumblr-square login-with"></i></a>#}
{#			        		<a href="#"><i class="fa fa-github-square login-with"></i></a>#}
{#		        		</div>		        		#}
{#		        	</div>#}
{#		        </div>#}
		      </form>
		      <div class="text-center">
		      	<a href="/register/view" class="templatemo-create-new">Create new account</a>
		      </div>
		</div>
	</div>
<div class="bottom">
    <a href="http://beian.miit.gov.cn" target="_blank">沪ICP备19029249号-1</a>
</div>
</body>
</html>

templates/profile.html
{% extends "topic/base.html" %}
{% block title %}个人资料{% endblock%}
{% block main %}
    <div id="main">
    <div>
        <div id="sidebar">
        <div class="panel">
            <div class="header">
                <span class="col_fade">个人信息</span>
            </div>
            <div class="inner">
                <div class="user_card">
                    <div>
                        <a class="user_avatar">
                            <img src="{{ user.image }}">
                        </a>
                        <span class="user_name"><a class="dark">{{ user.username }}</a></span>

                            <div class="board clearfix">
                                <div class="floor">
                                    <span class="big">积分: 0 </span>
                                </div>
                            </div>
                            <div class="space clearfix"></div>
                            <span class="signature">
                                “

                                    {{ user.sign }}

                                ”
                            </span>
                    </div>
                </div>
            </div>
        </div>

        <div class="panel">
            <div class="inner">
                <a href="/topic" id="create_topic_btn">
                    <span class="span-success">发布话题</span>
                </a>
            </div>
        </div>
    </div>
        <div id='content'>
            <div class='panel'>
                <div class='header'>
                    <ul class='breadcrumb'>
                        <li><a href='/topic'>主页</a><span class='divider'>/</span></li>
                    </ul>
                </div>
                <div class='inner userinfo'>
                    <div class='user_big_avatar'>
                        <img src="{{ user.image }}" class="user_big_avatar" title="{{ user.username }}">
                    </div>
                    <a class="dark">{{ user.username }}</a>

                    <p class="col_fade">{{ user.created_time | format_time }}</p>

                </div>
            </div>

            <div class='panel'>
                <div class='header'>
                    <span class='col_fade'>最近创建的话题</span>
                </div>

                {# 创建话题版面 #}
                {% for t in created %}
                <div class="cell">

                    <a class="user_avatar pull-left">
                        <img src="{{ user.image }}">
                    </a>

                    <span class="reply_count pull-left">
                        <span class="count_of_replies" title="回复数">
                            {{ t.replies() | count }}
                        </span>
                        <span class="count_seperator">/</span>
                        <span class="count_of_visits" title="点击数">
                            {{ t.views }}
                        </span>
                    </span>


                    <a class="last_time pull-right" >
                        <img class="user_small_avatar" src="{{ user.image }}">
                        <span class="last_active_time">{{ t.created_time | format_time }}</span>
                    </a>

                    <div class="topic_title_wrapper">
                        <a class="topic_title" href="{{ url_for('topic.detail', id=t.id) }}">
                                    {{ t.title }}
                        </a>
                    </div>
                </div>
                {% endfor %}

            </div>

            <div class='panel'>
                <div class='header'>
                    <span class='col_fade'>最近参与的话题</span>
                 </div>
                {# 参与话题版面 #}
                {% for r in replied %}
                <div class="cell">

                    <span class="reply_count pull-left">
                        <span class="count_of_replies" title="回复数">
                            {{ r.replies() | count }}
                        </span>
                        <span class="count_seperator">/</span>
                        <span class="count_of_visits" title="点击数">
                            {{ r.views }}
                        </span>
                    </span>


                    <a class="last_time pull-right">
                        <span class="last_active_time">{{ r.created_time | format_time }}</span>
                    </a>

                    <div class="topic_title_wrapper">

                        <a class="topic_title" href="{{ url_for('topic.detail', id=r.id) }}">
                            {{ r.title }}
                        </a>
                    </div>
                </div>
                {% endfor %}

            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/reset.html
<!DOCTYPE html>
<head>
	<title>Forgot Password</title>
	<meta name="keywords" content="" />
	<meta name="description" content="" />
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">

	<link href="/static/css-1/font-awesome.min.css" rel="stylesheet" type="text/css">
	<link href="/static/css-1/bootstrap.min.css" rel="stylesheet" type="text/css">
	<link href="/static/css-1/bootstrap-theme.min.css" rel="stylesheet" type="text/css">
	<link href="/static/css-1/templatemo_style.css" rel="stylesheet" type="text/css">
    <link href="/static/css/style.css" rel="stylesheet" type="text/css">
</head>
<body class="templatemo-bg-gray">
	<div class="container">
		<div class="col-md-12">
			<h1 class="margin-bottom-15">Password Reset</h1>
			<form class="form-horizontal templatemo-forgot-password-form templatemo-container" role="form" action="/reset/update" method="post">
				<div class="form-group">
		          <div class="col-md-12">
		          	Please enter your password that you can remember.
		          </div>
		        </div>
		        <div class="form-group">
		          	<div class="control-wrapper">
{#		            	<label for="password" class="control-label fa-label"><i class="fa fa-lock fa-medium"></i></label>#}
		            	<input type="password" class="form-control" id="password" placeholder="password" name="password">
		            </div>
		        </div>
		        <div class="form-group">
		          <div class="col-md-12">
		            <input type="submit" value="Submit" class="btn btn-danger">
                    <br><br>
                    <a href="/">or Login</a>
{#                    <a href="login-2.html">Login Two</a>#}
		          </div>
		        </div>
		      </form>
		</div>
	</div>
<div class="bottom">
    <a href="http://beian.miit.gov.cn" target="_blank">沪ICP备19029249号-1</a>
</div>
</body>
</html>

templates/setting.html
{% extends "topic/base.html" %}
{% block title %}个人信息{% endblock%}
{% block main %}
<div id="main">
    {#边栏#}
    <div id="sidebar">
        <div class="panel">
            <div class="header">
                <span class="col_fade">个人信息</span>
            </div>
            <div class="inner">
                <div class="user_card">
                    <div>
                        <a class="user_avatar">
                            <img src="{{ user.image }}">
                        </a>
                        <span class="user_name"><a class="dark">{{ user.username }}</a></span>

                            <div class="board clearfix">
                                <div class="floor">
                                    <span class="big">积分: 0 </span>
                                </div>
                            </div>
                            <div class="space clearfix"></div>
                            <span class="signature">
                                “

                                    {{ user.sign }}

                                ”
                            </span>
                    </div>
                </div>
            </div>
        </div>

        <div class="panel">
            <div class="inner">
                <a href="/topic" id="create_topic_btn">
                    <span class="span-success">发布话题</span>
                </a>
            </div>
        </div>
    </div>
    {#内容栏#}
    <div id="content">
        {#用户名修改#}
        <div class='panel'>
            <div class="header">
                <span class="col_fade">基础信息</span>
            </div>
            <div class="inner">
                <form method="post" action="{{ url_for('setting.re_info')}}">
                    <label class="control-label">用户名</label>
                    <input type="text" class="input-xlarge" name="username">
                    <label class="control-label">个人介绍</label>
                    <input type="text" class="input-xlarge" name="sign">
                    <button type="submit">提交</button>
                </form>
            </div>
        </div>
        {#密码修改#}
        <div class='panel'>
            <div class="header">
                <span class="col_fade">修改密码</span>
            </div>
            <div class="inner">
                <form method="post" action="/setting/password">
                    <input type="text" class="input-xlarge" name="password">
                <button type="submit">提交</button>
                </form>
            </div>
        </div>
        {#头像修改#}
        <div class='panel'>
            <div class="header">
                <span class="col_fade">设置头像</span>
            </div>
            <div class="inner">
                <form method="post"
                  action="{{ url_for('setting.avatar_add')}}"
                  enctype="multipart/form-data"
                >
                <input type="file" name="avatar">
                <button type="submit">上传头像</button>
                </form>
            </div>
        </div>
    </div>
</div>
{#    <img src="{{ user.image }} ">#}
{% endblock %}